services:
  frontend:
    build: ./frontend/react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend/c01-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: pictures
      MONGO_URI: mongodb://mongodb:27017/mydatabase
    depends_on:
      - jms-broker
      - database
      - mongodb
    networks:
      - app-network

  jms-broker:
    build: ./backend/c02-jms-broker
    ports:
      - "61616:61616"  # JMS Broker port
      - "8161:8161"    # ActiveMQ Admin Console (http://localhost:8161)
    networks:
      - app-network

  mdb:
    build: ./backend/c03-mdb
    depends_on:
      - jms-broker
      - rmi-server-1
      - rmi-server-2
    networks:
      - app-network

  rmi-server-1:
    build: ./backend/c04-rmi-server-1
    ports:
      - "1099:1099"  # Default RMI port
    networks:
      - app-network

  rmi-server-2:
    build: ./backend/c05-rmi-server-2
    ports:
      - "1100:1099"  # Maps internal 1099 to external 1100
    networks:
      - app-network

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pictures
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  db_data:
  mongo_data:

networks:
  app-network:
    driver: bridge
