version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Path to your backend Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql  # MySQL container hostname
      MYSQL_PORT: 3306
      MYSQL_DATABASE: zoomed_images
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Path to your frontend Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zoomed_images
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql file for DB initialization
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
